spring.application.name=U6L4
spring.datasource.url=jdbc:postgresql://localhost:5432/U6L4
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=3001
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.config.import=optional:file:./env.properties
